import React, { createContext, useContext, useState } from "react";

export const translations = {
  en: {
    code: "en", name: "English", flag: "🇬🇧",
    appTagline: "Your AI Investment Friend",
    appSub: "Smart investing for every Indian",
    getStarted: "Get Started →",
    selectLang: "Choose your language",
    selectLangSub: "The AI will respond in your chosen language",
    continue: "Continue →",
    next: "Next →",
    startInvesting: "Start Investing 🚀",
    dataPrivacy: "🔒 Your data stays private on your device.",
    step1Q: "What's your name? 👋",
    step1Sub: "Let's personalise your experience",
    step1Ph: "e.g. Rahul, Priya, Amit...",
    step2Q: "Your profession? 💼",
    step2Sub: "Helps us understand your financial situation",
    step3Q: "Monthly investment budget? 💰",
    step3Sub: "We'll suggest plans that fit your budget",
    step4Q: "How much risk are you okay with? ⚖️",
    step4Sub: "This shapes which funds we recommend",
    step5Q: "What's your main goal? 🎯",
    step5Sub: "We'll build a plan around it",
    riskLow: "🛡️ Low Risk", riskLowSub: "Safe, steady returns (FD, Liquid Funds)",
    riskMed: "⚖️ Medium Risk", riskMedSub: "Balanced growth (Large Cap, Hybrid)",
    riskHigh: "🚀 High Risk", riskHighSub: "Maximum growth (Small Cap, ELSS)",
    profStudent: "🎓 Student", profSalaried: "💼 Salaried",
    profSelf: "🧑‍💻 Self-Employed", profBusiness: "🏪 Business Owner",
    profHomemaker: "🏠 Homemaker", profRetired: "🌅 Retired",
    range1: "Up to ₹500", range2: "₹500 – ₹1,000",
    range3: "₹1,000 – ₹5,000", range4: "₹5,000 – ₹10,000", range5: "₹10,000+",
    goalEmergency: "🆘 Emergency Fund", goalVacation: "✈️ Vacation",
    goalEducation: "🎓 Education", goalHome: "🏠 Buy a Home",
    goalMarriage: "💍 Marriage", goalRetirement: "🌅 Retirement",
    navHome: "Home", navChat: "AI Chat", navExplore: "Explore",
    navPortfolio: "Portfolio", navGoals: "Goals",
    greeting: "Hello",
    totalPortfolio: "Total Portfolio Value",
    totalInvested: "Invested", totalGain: "Total Gain",
    askAI: "Ask AI", askAISub: "Get smart advice",
    exploreFunds: "Explore Funds", exploreSub: "Find investments",
    myPortfolio: "Portfolio", portfolioSub: "Track returns",
    myGoals: "My Goals", goalsSub: "Plan ahead",
    topHoldings: "Top Holdings", dailyTip: "Daily Tip",
    chatReady: "● Online — Ready to help",
    chatInput: "Type your question...",
    chatWelcome: (name) => `Hello ${name}! 👋 I'm NiveshSaathi, your AI investment friend.\n\nYou can ask me:\n• "Where should I invest ₹5,000?"\n• "What is SIP?"\n• "I need ₹1 lakh in 3 years"\n\nHow can I help you today? 😊`,
    quickQ1: "Where to invest ₹5,000?", quickQ2: "What is SIP?",
    quickQ3: "Suggest low risk funds", quickQ4: "How to build emergency fund?",
    exploreFundsTitle: "Explore Funds",
    exploreFundsSub: "Find the right investment for your goal",
    riskAppetite: "Risk Appetite", investPeriod: "Investment Period",
    periodShort: "< 1 Year", periodMed: "1–3 Years", periodLong: "3+ Years",
    showRec: "Show Recommendations →", topPick: "⭐ TOP PICK",
    minAmount: "Min Amount", lockIn: "Lock-in", returns: "Expected Returns",
    investBtn: "Invest in",
    sipCalc: "SIP Growth Calculator", monthly: "Monthly (₹)",
    years: "Years", returnRate: "Return Rate (%)", calculate: "Calculate →",
    totalInv: "Total Invested", estValue: "Est. Future Value", estGain: "Est. Gain",
    disclaimer: "⚠️ Mutual fund investments are subject to market risks. Past returns don't guarantee future results.",
    portfolioTitle: "My Portfolio", portfolioSub2: "Track all your investments",
    currentValue: "Current Value", invested2: "Invested", gain: "Gain",
    allReturns: "Total Returns", allocation: "Asset Allocation",
    holdings: "All Holdings", addMore: "+ Add More", withdraw: "Withdraw",
    annualReturns: "Annual Returns",
    goalsTitle: "My Goals", goalsSub2: "Plan and track your financial future",
    achieved: "% achieved", remaining: "remaining",
    addGoal: "+ Add New Goal",
    monthlyNeeded: "Invest", monthlyNeededSuf: "/month in SIP to reach this goal on time.",
  },

  hi: {
    code: "hi", name: "हिन्दी (Hinglish)", flag: "🇮🇳",
    appTagline: "Aapka AI Investment Dost",
    appSub: "Har Indian ke liye smart investing",
    getStarted: "Shuru Karein →",
    selectLang: "Apni bhasha chuniye",
    selectLangSub: "AI aapki chosen bhasha mein jawab dega",
    continue: "Aage →",
    next: "Aage →",
    startInvesting: "Invest Shuru Karein 🚀",
    dataPrivacy: "🔒 Aapka data private rehta hai.",
    step1Q: "Aapka naam kya hai? 👋",
    step1Sub: "Aapko jaanne ki koshish karte hain",
    step1Ph: "jaise Rahul, Priya, Amit...",
    step2Q: "Aap kya karte hain? 💼",
    step2Sub: "Aapki financial situation samajhne mein help karta hai",
    step3Q: "Monthly kitna invest kar sakte hain? 💰",
    step3Sub: "Budget ke hisaab se plan suggest karenge",
    step4Q: "Kitna risk le sakte hain? ⚖️",
    step4Sub: "Isse sahi funds recommend karenge",
    step5Q: "Main goal kya hai? 🎯",
    step5Sub: "Iske around plan banayenge",
    riskLow: "🛡️ Low Risk", riskLowSub: "Safe returns (FD, Liquid Funds)",
    riskMed: "⚖️ Medium Risk", riskMedSub: "Balanced growth (Large Cap, Hybrid)",
    riskHigh: "🚀 High Risk", riskHighSub: "Maximum growth (Small Cap, ELSS)",
    profStudent: "🎓 Student", profSalaried: "💼 Naukri",
    profSelf: "🧑‍💻 Self-Employed", profBusiness: "🏪 Business Owner",
    profHomemaker: "🏠 Homemaker", profRetired: "🌅 Retired",
    range1: "₹500 tak", range2: "₹500 – ₹1,000",
    range3: "₹1,000 – ₹5,000", range4: "₹5,000 – ₹10,000", range5: "₹10,000+",
    goalEmergency: "🆘 Emergency Fund", goalVacation: "✈️ Trip",
    goalEducation: "🎓 Padhai", goalHome: "🏠 Ghar Kharidna",
    goalMarriage: "💍 Shaadi", goalRetirement: "🌅 Retirement",
    navHome: "Home", navChat: "AI Chat", navExplore: "Explore",
    navPortfolio: "Portfolio", navGoals: "Goals",
    greeting: "Namaste",
    totalPortfolio: "Total Portfolio Value",
    totalInvested: "Invested", totalGain: "Total Gain",
    askAI: "AI Se Poochein", askAISub: "Smart advice lo",
    exploreFunds: "Funds Dekho", exploreSub: "Investment dhundho",
    myPortfolio: "Portfolio", portfolioSub: "Returns track karo",
    myGoals: "Mere Goals", goalsSub: "Planning karo",
    topHoldings: "Top Holdings", dailyTip: "Aaj Ki Tip",
    chatReady: "● Online — Help ke liye tayaar",
    chatInput: "Apna sawaal likhein...",
    chatWelcome: (name) => `Namaste ${name}! 👋 Main NiveshSaathi hoon — aapka AI investment dost.\n\nAap mujhse pooch sakte hain:\n• "₹5,000 kahan invest karoon?"\n• "SIP kya hoti hai?"\n• "Mujhe 3 saal mein ₹1 lakh chahiye"\n\nBataiye, kaise help karoon? 😊`,
    quickQ1: "₹5,000 kahan invest karoon?", quickQ2: "SIP kya hoti hai?",
    quickQ3: "Low risk funds batao", quickQ4: "Emergency fund kaise banayein?",
    exploreFundsTitle: "Funds Explore Karein",
    exploreFundsSub: "Apne goal ke liye sahi investment dhundho",
    riskAppetite: "Risk Appetite", investPeriod: "Kitne Time Ke Liye?",
    periodShort: "1 Saal Se Kam", periodMed: "1–3 Saal", periodLong: "3+ Saal",
    showRec: "Recommendations Dikhao →", topPick: "⭐ TOP PICK",
    minAmount: "Min Amount", lockIn: "Lock-in", returns: "Expected Returns",
    investBtn: "Invest Karein",
    sipCalc: "SIP Growth Calculator", monthly: "Monthly (₹)",
    years: "Saal", returnRate: "Return Rate (%)", calculate: "Calculate Karein →",
    totalInv: "Total Invest Hoga", estValue: "Est. Future Value", estGain: "Est. Gain",
    disclaimer: "⚠️ Mutual fund investments market risks ke subject hain. Past returns future results guarantee nahi karte.",
    portfolioTitle: "Mera Portfolio", portfolioSub2: "Saari investments track karein",
    currentValue: "Current Value", invested2: "Invested", gain: "Gain",
    allReturns: "Total Returns", allocation: "Asset Allocation",
    holdings: "Saari Holdings", addMore: "+ Aur Invest Karein", withdraw: "Withdraw Karein",
    annualReturns: "Annual Returns",
    goalsTitle: "Mere Goals", goalsSub2: "Financial future ki planning karein",
    achieved: "% achieve hua", remaining: "bacha hai",
    addGoal: "+ Naya Goal Add Karein",
    monthlyNeeded: "Invest karein", monthlyNeededSuf: "/month SIP mein is goal tak pahunchne ke liye.",
  },

  te: {
    code: "te", name: "తెలుగు (Tenglish)", flag: "🏳️",
    appTagline: "Meeru AI Investment Mitra",
    appSub: "Prati Indian ki smart investing",
    getStarted: "Prarambhinchu →",
    selectLang: "Meeru bhasha erchukondi",
    selectLangSub: "AI meeru chosen bhashalO matladutundi",
    continue: "Tarvata →",
    next: "Tarvata →",
    startInvesting: "Invest Prarambhinchu 🚀",
    dataPrivacy: "🔒 Meeru data private ga untundi.",
    step1Q: "Meeru peru enti? 👋",
    step1Sub: "Meeru gurinchi telusustunam",
    step1Ph: "udaa. Ravi, Priya, Amit...",
    step2Q: "Meeru emii chestaru? 💼",
    step2Sub: "Meeru financial situation artham chesukuntamu",
    step3Q: "Nela navata enta invest cheyyagalaru? 💰",
    step3Sub: "Budget ki taginattu plans suggest chestamu",
    step4Q: "Enta risk tesukogalaru? ⚖️",
    step4Sub: "Idii sari funds chupistundi",
    step5Q: "Mukhya goal emiti? 🎯",
    step5Sub: "Daani chuttu plan nirmistamu",
    riskLow: "🛡️ Takkuva Risk", riskLowSub: "Safe returns (FD, Liquid Funds)",
    riskMed: "⚖️ Madhyama Risk", riskMedSub: "Balanced growth (Large Cap, Hybrid)",
    riskHigh: "🚀 Ekkuva Risk", riskHighSub: "Maximum growth (Small Cap, ELSS)",
    profStudent: "🎓 Student", profSalaried: "💼 Naukari",
    profSelf: "🧑‍💻 Self-Employed", profBusiness: "🏪 Business Owner",
    profHomemaker: "🏠 Gruhalakshmi", profRetired: "🌅 Retired",
    range1: "₹500 varaku", range2: "₹500 – ₹1,000",
    range3: "₹1,000 – ₹5,000", range4: "₹5,000 – ₹10,000", range5: "₹10,000+",
    goalEmergency: "🆘 Emergency Fund", goalVacation: "✈️ Prayanam",
    goalEducation: "🎓 Chadduvulu", goalHome: "🏠 Intlu Konugatam",
    goalMarriage: "💍 Pelli", goalRetirement: "🌅 Retirement",
    navHome: "Home", navChat: "AI Chat", navExplore: "Explore",
    navPortfolio: "Portfolio", navGoals: "Goals",
    greeting: "Namaskaram",
    totalPortfolio: "Total Portfolio Viluva",
    totalInvested: "Invest Chesindi", totalGain: "Total Labham",
    askAI: "AI Adugandi", askAISub: "Salaha teesukundi",
    exploreFunds: "Funds Choosandi", exploreSub: "Investment velukuli",
    myPortfolio: "Portfolio", portfolioSub: "Returns track cheyyandi",
    myGoals: "Naa Goals", goalsSub: "Planning cheyyandi",
    topHoldings: "Top Holdings", dailyTip: "Neti Tip",
    chatReady: "● Online — Sahayam cheyyataniki ready",
    chatInput: "Meeru prashna rayyandi...",
    chatWelcome: (name) => `Namaskaram ${name}! 👋 Nenu NiveshSaathi — meeru AI investment mitra.\n\nMeeru nanu adugavacchu:\n• "₹5,000 ekkada invest cheyyali?"\n• "SIP ante emiti?"\n• "3 sarallO naku ₹1 lakh kaavali"\n\nCheppandi, ela help cheyyali? 😊`,
    quickQ1: "₹5,000 ekkada invest cheyyali?", quickQ2: "SIP ante emiti?",
    quickQ3: "Takkuva risk funds cheppandi", quickQ4: "Emergency fund ela nirlinchaali?",
    exploreFundsTitle: "Funds Explore Cheyyandi",
    exploreFundsSub: "Meeru goal ki taginattu investment velukuli",
    riskAppetite: "Risk Sahana", investPeriod: "Enta Kalam?",
    periodShort: "1 Sari Kante Takkuva", periodMed: "1–3 Sarulu", periodLong: "3+ Sarulu",
    showRec: "Recommendations Chupinchu →", topPick: "⭐ TOP PICK",
    minAmount: "Min Amount", lockIn: "Lock-in", returns: "Anumaanitamai Returns",
    investBtn: "Invest Cheyyandi",
    sipCalc: "SIP Growth Calculator", monthly: "Nela navata (₹)",
    years: "Sarulu", returnRate: "Return Rate (%)", calculate: "Calculate Cheyyandi →",
    totalInv: "Total Invest Avutundi", estValue: "Est. Future Viluva", estGain: "Est. Labham",
    disclaimer: "⚠️ Mutual fund investments market risks ki subject avutaayi. Past returns future ki guarantee ivvavu.",
    portfolioTitle: "Naa Portfolio", portfolioSub2: "Anni investments track cheyyandi",
    currentValue: "Prasta Viluva", invested2: "Invest Chesindi", gain: "Labham",
    allReturns: "Total Returns", allocation: "Asset Kethaayi",
    holdings: "Holdings", addMore: "+ Ekkuva Add Cheyyandi", withdraw: "Withdraw",
    annualReturns: "Annual Returns",
    goalsTitle: "Naa Goals", goalsSub2: "Financial future plan mariyu track cheyyandi",
    achieved: "% saadhinchamu", remaining: "migili undi",
    addGoal: "+ Kotha Goal Add Cheyyandi",
    monthlyNeeded: "Invest cheyyandi", monthlyNeededSuf: "/nela SIP lO i goal ki.",
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState("en");
  const t = translations[lang] || translations.en;
  return (
    <LanguageContext.Provider value={{ lang, setLang, t, translations }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  return useContext(LanguageContext);
}

export default translations;