// src/context/LanguageContext.js
import React, { createContext, useContext, useState } from "react";

const translations = {
  en: {
    code: "en",
    name: "English",
    flag: "🇬🇧",
    // Onboarding
    appTagline: "Your AI Investment Friend",
    selectLang: "Choose your language",
    selectLangSub: "Pick the language you're most comfortable with",
    continue: "Continue",
    next: "Next →",
    startInvesting: "Start Investing 🚀",
    dataPrivacy: "🔒 Your data stays on your device. We don't share it.",
    // Onboarding steps
    step1Q: "What's your name? 👋",
    step1Sub: "Let's get to know you",
    step1Ph: "e.g. Rahul, Priya, Amit...",
    step2Q: "How much do you want to invest? 💰",
    step2Sub: "Monthly SIP amount or one-time investment",
    step2Ph: "e.g. 5000",
    step3Q: "How much risk can you take? ⚖️",
    step3Sub: "This helps us pick the right funds for you",
    riskLow: "🛡️ Low Risk",
    riskLowSub: "Safe, steady returns (FD, Liquid Funds)",
    riskMed: "⚖️ Medium Risk",
    riskMedSub: "Balanced growth (Large Cap, Hybrid)",
    riskHigh: "🚀 High Risk",
    riskHighSub: "Maximum growth (Small Cap, ELSS)",
    step4Q: "What's your main goal? 🎯",
    step4Sub: "What are you investing for?",
    goalEmergency: "🆘 Emergency Fund",
    goalVacation: "✈️ Vacation",
    goalEducation: "🎓 Child Education",
    goalHome: "🏠 Buy a Home",
    goalMarriage: "💍 Marriage",
    goalRetirement: "🌅 Retirement",
    // Nav
    navHome: "Home",
    navChat: "AI Chat",
    navExplore: "Explore",
    navPortfolio: "Portfolio",
    navGoals: "Goals",
    // Dashboard
    greeting: "Hello",
    totalPortfolio: "Total Portfolio Value",
    totalInvested: "Invested",
    totalGain: "Total Gain",
    askAI: "Ask AI",
    askAISub: "Get smart advice",
    exploreFunds: "Explore Funds",
    exploreSub: "Find investments",
    myPortfolio: "Portfolio",
    portfolioSub: "Track returns",
    myGoals: "My Goals",
    goalsSub: "Plan ahead",
    topHoldings: "Top Holdings",
    dailyTip: "Daily Tip",
    // Chat
    chatReady: "Online — Ready to help",
    chatInput: "Type your question...",
    chatWelcome: (name) => `Hello ${name}! 👋 I'm NiveshSaathi, your AI investment friend.\n\nYou can ask me:\n• "Where should I invest ₹5000?"\n• "What is SIP?"\n• "I need ₹1 lakh in 3 years"\n\nHow can I help you today? 😊`,
    quickQ1: "Where should I invest ₹5000?",
    quickQ2: "What is SIP?",
    quickQ3: "Suggest low risk funds",
    quickQ4: "How to build emergency fund?",
    // Explore
    exploreFundsTitle: "Explore Funds",
    exploreFundsSub: "Find the right investment for your goal",
    riskAppetite: "Risk Appetite",
    investPeriod: "Investment Period",
    periodShort: "< 1 Year",
    periodMed: "1–3 Years",
    periodLong: "3+ Years",
    showRec: "Show Recommendations →",
    topPick: "⭐ TOP PICK",
    minAmount: "Min Amount",
    lockIn: "Lock-in",
    returns: "Expected Returns",
    investBtn: "Invest in",
    disclaimer: "⚠️ Mutual fund investments are subject to market risks. Past returns don't guarantee future results. Please read all documents carefully.",
    // SIP Calculator
    sipCalc: "SIP Calculator",
    monthly: "Monthly Amount (₹)",
    years: "Investment Period (Years)",
    returnRate: "Expected Return Rate (%)",
    estimate: "Calculate",
    totalInv: "Total Invested",
    estValue: "Est. Future Value",
    estGain: "Estimated Gain",
    // Portfolio
    portfolioTitle: "My Portfolio",
    portfolioSub2: "Track all your investments",
    currentValue: "Current Value",
    invested2: "Invested",
    gain: "Gain",
    allReturns: "Total Returns",
    allocation: "Asset Allocation",
    holdings: "All Holdings",
    addMore: "+ Add More",
    withdraw: "Withdraw",
    annualReturns: "Annual Returns",
    // Goals
    goalsTitle: "My Goals",
    goalsSub2: "Plan and track your financial future",
    achieved: "% achieved",
    remaining: "remaining",
    addGoal: "+ Add New Goal",
    monthlyNeeded: "Invest",
    monthlyNeededSuf: "/month in SIP to reach this goal on time.",
  },

  hi: {
    code: "hi",
    name: "हिन्दी (Hinglish)",
    flag: "🇮🇳",
    appTagline: "Aapka AI Investment Dost",
    selectLang: "Apni bhasha chuniye",
    selectLangSub: "Woh bhasha chuniye jisme aap sabse comfortable hain",
    continue: "Aage Badhein",
    next: "Aage →",
    startInvesting: "Invest Shuru Karein 🚀",
    dataPrivacy: "🔒 Aapka data aapke device par rehta hai. Hum share nahi karte.",
    step1Q: "Aapka naam kya hai? 👋",
    step1Sub: "Aapko jaanne ki koshish karte hain",
    step1Ph: "jaise Rahul, Priya, Amit...",
    step2Q: "Kitna invest karna chahte hain? 💰",
    step2Sub: "Monthly SIP ya ek baar ki investment",
    step2Ph: "jaise 5000",
    step3Q: "Kitna risk le sakte hain? ⚖️",
    step3Sub: "Isse hum aapke liye sahi funds choose karenge",
    riskLow: "🛡️ Low Risk",
    riskLowSub: "Safe, steady returns (FD, Liquid Funds)",
    riskMed: "⚖️ Medium Risk",
    riskMedSub: "Balanced growth (Large Cap, Hybrid)",
    riskHigh: "🚀 High Risk",
    riskHighSub: "Maximum growth (Small Cap, ELSS)",
    step4Q: "Main goal kya hai? 🎯",
    step4Sub: "Kisliye invest karna chahte hain?",
    goalEmergency: "🆘 Emergency Fund",
    goalVacation: "✈️ Vacation / Trip",
    goalEducation: "🎓 Bacchon ki Padhai",
    goalHome: "🏠 Ghar Kharidna",
    goalMarriage: "💍 Shaadi",
    goalRetirement: "🌅 Retirement",
    navHome: "Home",
    navChat: "AI Chat",
    navExplore: "Explore",
    navPortfolio: "Portfolio",
    navGoals: "Goals",
    greeting: "Namaste",
    totalPortfolio: "Total Portfolio Value",
    totalInvested: "Invested",
    totalGain: "Total Gain",
    askAI: "AI Se Poochein",
    askAISub: "Smart advice lo",
    exploreFunds: "Funds Dekho",
    exploreSub: "Investment dhundho",
    myPortfolio: "Portfolio",
    portfolioSub: "Returns track karo",
    myGoals: "Mere Goals",
    goalsSub: "Aage ki planning",
    topHoldings: "Top Holdings",
    dailyTip: "Aaj Ki Tip",
    chatReady: "Online — Help ke liye tayaar",
    chatInput: "Apna sawaal likhein...",
    chatWelcome: (name) => `Namaste ${name}! 👋 Main NiveshSaathi hoon — aapka AI investment dost.\n\nAap mujhse pooch sakte hain:\n• "₹5000 kahan invest karoon?"\n• "SIP kya hoti hai?"\n• "Mujhe 3 saal mein ₹1 lakh chahiye"\n\nBataiye, kaise help kar sakta hoon? 😊`,
    quickQ1: "₹5000 kahan invest karoon?",
    quickQ2: "SIP kya hoti hai?",
    quickQ3: "Low risk funds batao",
    quickQ4: "Emergency fund kaise banayein?",
    exploreFundsTitle: "Funds Explore Karein",
    exploreFundsSub: "Apne goal ke liye sahi investment dhundho",
    riskAppetite: "Risk Appetite",
    investPeriod: "Kitne Time ke Liye?",
    periodShort: "< 1 Saal",
    periodMed: "1–3 Saal",
    periodLong: "3+ Saal",
    showRec: "Recommendations Dikhao →",
    topPick: "⭐ TOP PICK",
    minAmount: "Min Amount",
    lockIn: "Lock-in",
    returns: "Expected Returns",
    investBtn: "Invest karein",
    disclaimer: "⚠️ Mutual fund investments market risks ke subject hain. Past returns future results guarantee nahi karte. Sabhi documents dhyan se padhein.",
    sipCalc: "SIP Calculator",
    monthly: "Monthly Amount (₹)",
    years: "Kitne Saal?",
    returnRate: "Expected Return (%)",
    estimate: "Calculate Karein",
    totalInv: "Total Invest Hoga",
    estValue: "Est. Future Value",
    estGain: "Estimated Gain",
    portfolioTitle: "Mera Portfolio",
    portfolioSub2: "Saari investments track karein",
    currentValue: "Current Value",
    invested2: "Invested",
    gain: "Gain",
    allReturns: "Total Returns",
    allocation: "Asset Allocation",
    holdings: "Saari Holdings",
    addMore: "+ Aur Invest Karein",
    withdraw: "Withdraw Karein",
    annualReturns: "Annual Returns",
    goalsTitle: "Mere Goals",
    goalsSub2: "Apne financial future ki planning karein",
    achieved: "% achieve hua",
    remaining: "bacha hai",
    addGoal: "+ Naya Goal Add Karein",
    monthlyNeeded: "Invest karein",
    monthlyNeededSuf: "/month SIP mein is goal tak pahunchne ke liye.",
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState("en");
  const t = translations[lang] || translations.en;
  return (
    <LanguageContext.Provider value={{ lang, setLang, t, translations }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  return useContext(LanguageContext);
}

export default translations;